// Code generated by templ - DO NOT EDIT.

// templ: version: v0.3.1020
package platformadmin

//lint:file-ignore SA4006 This context is only used if a nested component is present.

import "github.com/a-h/templ"
import templruntime "github.com/a-h/templ/runtime"

func HomePage(view homeView) templ.Component {
	return templruntime.GeneratedTemplate(func(templ_7745c5c3_Input templruntime.GeneratedComponentInput) (templ_7745c5c3_Err error) {
		templ_7745c5c3_W, ctx := templ_7745c5c3_Input.Writer, templ_7745c5c3_Input.Context
		if templ_7745c5c3_CtxErr := ctx.Err(); templ_7745c5c3_CtxErr != nil {
			return templ_7745c5c3_CtxErr
		}
		templ_7745c5c3_Buffer, templ_7745c5c3_IsBuffer := templruntime.GetBuffer(templ_7745c5c3_W)
		if !templ_7745c5c3_IsBuffer {
			defer func() {
				templ_7745c5c3_BufErr := templruntime.ReleaseBuffer(templ_7745c5c3_Buffer)
				if templ_7745c5c3_Err == nil {
					templ_7745c5c3_Err = templ_7745c5c3_BufErr
				}
			}()
		}
		ctx = templ.InitializeContext(ctx)
		templ_7745c5c3_Var1 := templ.GetChildren(ctx)
		if templ_7745c5c3_Var1 == nil {
			templ_7745c5c3_Var1 = templ.NopComponent
		}
		ctx = templ.ClearChildren(ctx)
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 1, "<!doctype html><html lang=\"en\"><head><meta charset=\"UTF-8\"><meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\"><link rel=\"icon\" href=\"/static/favicon/favicon.ico\"><title>Platform Admin</title><link rel=\"stylesheet\" href=\"/static/platformadmin.v1.css\"></head><body class=\"platform-home-body\"><div class=\"platform-home\">")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = platformAdminSidebar("dashboard").Render(ctx, templ_7745c5c3_Buffer)
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 2, "<main class=\"platform-home-main\"><header class=\"platform-header platform-home-header\"><div><p class=\"platform-eyebrow\">System Overview</p><h1>Welcome, Admin</h1><p class=\"platform-copy\">Signed in as ")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		var templ_7745c5c3_Var2 string
		templ_7745c5c3_Var2, templ_7745c5c3_Err = templ.JoinStringErrs(view.Email)
		if templ_7745c5c3_Err != nil {
			return templ.Error{Err: templ_7745c5c3_Err, FileName: `home.templ`, Line: 21, Col: 57}
		}
		_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString(templ.EscapeString(templ_7745c5c3_Var2))
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 3, ". Here is the current pulse of SongDock.</p></div><form class=\"platform-home-logout-form\" method=\"post\" action=\"/platform/admin/logout\"><span class=\"platform-tooltip platform-home-logout-tooltip\" data-tooltip=\"Log out\"><button class=\"platform-home-logout\" type=\"submit\" aria-label=\"Log out\" title=\"Log out\"><svg class=\"platform-home-icon\" aria-hidden=\"true\"><use href=\"/static/lucide.svg#log-out\"></use></svg></button></span></form></header><section class=\"platform-home-actions\" aria-labelledby=\"platform-home-actions-title\"><h2 id=\"platform-home-actions-title\" class=\"platform-home-section-title\">Quick Actions</h2><div class=\"platform-home-action-grid\"><a class=\"platform-home-action-card\" href=\"/platform/admin/users\"><span class=\"platform-home-action-icon\"><svg class=\"platform-home-icon\" aria-hidden=\"true\"><use href=\"/static/lucide.svg#users\"></use></svg></span><h3>Manage Users</h3><p>Review users, send invitations, and manage access.</p></a> <a class=\"platform-home-action-card\" href=\"/platform/admin/artists\"><span class=\"platform-home-action-icon\"><svg class=\"platform-home-icon\" aria-hidden=\"true\"><use href=\"/static/lucide.svg#music\"></use></svg></span><h3>Manage Artists</h3><p>Create, manage, and delete artists.</p></a></div></section></main></div></body></html>")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		return nil
	})
}

var _ = templruntime.GeneratedTemplate
