package store

import (
	"database/sql"
	"fmt"
)

const postgresSchemaVersion = 1

func migratePostgres(db *sql.DB) error {
	tx, err := db.Begin()
	if err != nil {
		return err
	}
	defer tx.Rollback()

	statements := []string{
		`CREATE TABLE IF NOT EXISTS songdock_schema_migrations (
			version BIGINT PRIMARY KEY,
			applied_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
		)`,
		`CREATE TABLE IF NOT EXISTS artists (
			id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
			name TEXT NOT NULL,
			slug TEXT NOT NULL UNIQUE,
			meta_pixel_id TEXT NOT NULL DEFAULT ''
		)`,
		`CREATE TABLE IF NOT EXISTS users (
			id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
			email TEXT NOT NULL UNIQUE,
			password_hash TEXT NOT NULL
		)`,
		`CREATE TABLE IF NOT EXISTS user_token_revocations (
			user_id BIGINT PRIMARY KEY,
			revoked_at BIGINT NOT NULL
		)`,
		`CREATE TABLE IF NOT EXISTS songs (
			id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
			title TEXT NOT NULL,
			artist_name TEXT NOT NULL,
			description TEXT NOT NULL DEFAULT '',
			image_url TEXT NOT NULL DEFAULT '',
			artwork_path TEXT NOT NULL DEFAULT '',
			youtube_url TEXT NOT NULL DEFAULT '',
			spotify_url TEXT NOT NULL DEFAULT '',
			apple_music_url TEXT NOT NULL DEFAULT '',
			song_slug TEXT NOT NULL,
			artist_id BIGINT NOT NULL REFERENCES artists(id),
			UNIQUE (artist_id, song_slug)
		)`,
		`CREATE TABLE IF NOT EXISTS user_artists (
			user_id BIGINT NOT NULL REFERENCES users(id),
			artist_id BIGINT NOT NULL REFERENCES artists(id),
			PRIMARY KEY (user_id, artist_id)
		)`,
		`CREATE TABLE IF NOT EXISTS user_invitations (
			id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
			email TEXT NOT NULL UNIQUE,
			artist_id BIGINT NOT NULL REFERENCES artists(id),
			invitation_code_hash TEXT NOT NULL,
			created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
			accepted_at TIMESTAMPTZ,
			expires_at TIMESTAMPTZ,
				revoked_at TIMESTAMPTZ
		)`,
		`ALTER TABLE artists ADD COLUMN IF NOT EXISTS meta_pixel_id TEXT NOT NULL DEFAULT ''`,
		`ALTER TABLE songs ADD COLUMN IF NOT EXISTS description TEXT NOT NULL DEFAULT ''`,
		`ALTER TABLE songs ADD COLUMN IF NOT EXISTS image_url TEXT NOT NULL DEFAULT ''`,
		`ALTER TABLE songs ADD COLUMN IF NOT EXISTS artwork_path TEXT NOT NULL DEFAULT ''`,
		`ALTER TABLE songs ADD COLUMN IF NOT EXISTS youtube_url TEXT NOT NULL DEFAULT ''`,
		`ALTER TABLE songs ADD COLUMN IF NOT EXISTS spotify_url TEXT NOT NULL DEFAULT ''`,
		`ALTER TABLE songs ADD COLUMN IF NOT EXISTS apple_music_url TEXT NOT NULL DEFAULT ''`,
	}
	for _, statement := range statements {
		if _, err := tx.Exec(statement); err != nil {
			return fmt.Errorf("postgres migration statement: %w", err)
		}
	}
	if err := migratePostgresLegacyColumns(tx); err != nil {
		return err
	}
	for _, statement := range []string{
		`CREATE UNIQUE INDEX IF NOT EXISTS users_email_lower_unique ON users (lower(email))`,
		`CREATE UNIQUE INDEX IF NOT EXISTS user_invitations_email_lower_unique ON user_invitations (lower(email))`,
		`CREATE UNIQUE INDEX IF NOT EXISTS user_invitations_code_hash_unique ON user_invitations (invitation_code_hash)`,
		`CREATE UNIQUE INDEX IF NOT EXISTS songs_artist_song_slug_unique ON songs (artist_id, song_slug)`,
		`INSERT INTO songdock_schema_migrations (version) VALUES (1) ON CONFLICT (version) DO NOTHING`,
	} {
		if _, err := tx.Exec(statement); err != nil {
			return fmt.Errorf("postgres migration statement: %w", err)
		}
	}

	var version int
	if err := tx.QueryRow(`SELECT COALESCE(MAX(version), 0) FROM songdock_schema_migrations`).Scan(&version); err != nil {
		return err
	}
	if version < postgresSchemaVersion {
		return fmt.Errorf("postgres schema version %d is older than required version %d", version, postgresSchemaVersion)
	}
	return tx.Commit()
}

func migratePostgresLegacyColumns(tx *sql.Tx) error {
	songColumns, err := postgresTableColumns(tx, "songs")
	if err != nil {
		return err
	}
	if _, hasArtistID := songColumns["artist_id"]; !hasArtistID {
		if _, err := tx.Exec(`ALTER TABLE songs ADD COLUMN artist_id BIGINT REFERENCES artists(id)`); err != nil {
			return fmt.Errorf("add songs artist reference: %w", err)
		}
		if _, hasArtistSlug := songColumns["artist_slug"]; hasArtistSlug {
			if _, err := tx.Exec(`
				INSERT INTO artists (name, slug)
				SELECT DISTINCT artist_name, artist_slug FROM songs
				ON CONFLICT (slug) DO UPDATE SET name = EXCLUDED.name`); err != nil {
				return fmt.Errorf("backfill postgres artists: %w", err)
			}
			if _, err := tx.Exec(`
				UPDATE songs s SET artist_id = a.id
				  FROM artists a
				 WHERE s.artist_id IS NULL AND a.slug = s.artist_slug`); err != nil {
				return fmt.Errorf("backfill postgres song artists: %w", err)
			}
		}
		var missing int
		if err := tx.QueryRow(`SELECT COUNT(*) FROM songs WHERE artist_id IS NULL`).Scan(&missing); err != nil {
			return err
		}
		if missing > 0 {
			return fmt.Errorf("postgres migration cannot backfill %d songs without an artist", missing)
		}
		if _, err := tx.Exec(`ALTER TABLE songs ALTER COLUMN artist_id SET NOT NULL`); err != nil {
			return fmt.Errorf("require postgres song artist reference: %w", err)
		}
	}

	userColumns, err := postgresTableColumns(tx, "users")
	if err != nil {
		return err
	}
	if _, hasArtistID := userColumns["artist_id"]; hasArtistID {
		if _, err := tx.Exec(`
			INSERT INTO user_artists (user_id, artist_id)
			SELECT id, artist_id FROM users WHERE artist_id IS NOT NULL
			ON CONFLICT (user_id, artist_id) DO NOTHING`); err != nil {
			return fmt.Errorf("backfill postgres user artists: %w", err)
		}
	}

	invitationsColumns, err := postgresTableColumns(tx, "user_invitations")
	if err != nil {
		return err
	}
	if _, hasArtistID := invitationsColumns["artist_id"]; !hasArtistID {
		if _, err := tx.Exec(`ALTER TABLE user_invitations ADD COLUMN artist_id BIGINT REFERENCES artists(id)`); err != nil {
			return fmt.Errorf("add postgres invitation artist reference: %w", err)
		}
		var missing int
		if err := tx.QueryRow(`SELECT COUNT(*) FROM user_invitations WHERE artist_id IS NULL`).Scan(&missing); err != nil {
			return err
		}
		if missing > 0 {
			return fmt.Errorf("postgres migration cannot backfill %d invitations without an artist", missing)
		}
		if _, err := tx.Exec(`ALTER TABLE user_invitations ALTER COLUMN artist_id SET NOT NULL`); err != nil {
			return fmt.Errorf("require postgres invitation artist reference: %w", err)
		}
	}
	return nil
}

func postgresTableColumns(tx *sql.Tx, table string) (map[string]struct{}, error) {
	rows, err := tx.Query(`
		SELECT column_name FROM information_schema.columns
		 WHERE table_schema = current_schema() AND table_name = $1`, table)
	if err != nil {
		return nil, fmt.Errorf("inspect postgres table %q: %w", table, err)
	}
	defer rows.Close()
	columns := make(map[string]struct{})
	for rows.Next() {
		var column string
		if err := rows.Scan(&column); err != nil {
			return nil, fmt.Errorf("scan postgres table %q: %w", table, err)
		}
		columns[column] = struct{}{}
	}
	return columns, rows.Err()
}

func validatePostgresSchema(db *sql.DB) error {
	for _, table := range []string{"songdock_schema_migrations", "artists", "users", "songs", "user_artists", "user_invitations"} {
		var exists bool
		if err := db.QueryRow(`SELECT to_regclass($1) IS NOT NULL`, table).Scan(&exists); err != nil {
			return fmt.Errorf("check postgres schema: %w", err)
		}
		if !exists {
			return fmt.Errorf("postgres schema is missing table %q; run songdock migrate up", table)
		}
	}
	var version int
	if err := db.QueryRow(`SELECT COALESCE(MAX(version), 0) FROM songdock_schema_migrations`).Scan(&version); err != nil {
		return fmt.Errorf("check postgres schema version: %w", err)
	}
	if version < postgresSchemaVersion {
		return fmt.Errorf("postgres schema version %d is older than required version %d; run songdock migrate up", version, postgresSchemaVersion)
	}
	return nil
}

func validateSQLiteSchema(db *sql.DB) error {
	var count int
	if err := db.QueryRow(
		`SELECT COUNT(*) FROM sqlite_master WHERE type = 'table' AND name IN ('artists', 'users', 'songs', 'user_artists', 'user_invitations')`,
	).Scan(&count); err != nil {
		return fmt.Errorf("check sqlite schema: %w", err)
	}
	if count != 5 {
		return fmt.Errorf("sqlite schema is missing required tables; run songdock migrate up")
	}
	return nil
}
